### ISSUE TITLE
Turning

### ISSUE THREAD

**Issue by Jjoiner729** [camren-m/XboxWheelCompatibility#1]
I tried turning and I just doesnt work no matter what i try to do

**Comment by whytrabyt** [comment]
@Jjoiner729 Can you tell me how you even got it to work? I get nothing what so ever. Just I new device under Other Devices called Xbox Virtual Game Controller. Any help would be nice

**Comment by Jjoiner729** [comment]
sorry i had to type fast but when i try steering it just doesnt work like if i move it even an inch either way it just thinks the wheel did a full rotations also the break peddal just doesnt work

**Comment by camren-m** [comment]
> sorry i had to type fast but when i try steering it just doesnt work like if i move it even an inch either way it just thinks the wheel did a full rotations also the break peddal just doesnt work

Do you happen to have the Xbox 360 gamepad drivers installed? (the ones featured in the linus tech tips forum, if you came from there)

**Comment by Jjoiner729** [comment]
yes I do

**Comment by Jjoiner729** [comment]
whenever i run the xboxwheelcompatability.exe it just says i have raw imput controllers and no active wheeles is that my issue?

**Comment by camren-m** [comment]
> yes I do

Try uninstalling those and trying to start the software again.

**Comment by Jjoiner729** [comment]
im not gonna lie to you ive done that like 5 times dead ass

**Comment by camren-m** [comment]
> im not gonna lie to you ive done that like 5 times dead ass

Alright, try unplugging your wheel, checking the amount of raw game controllers, and then plugging your wheel back in and checking the amount of raw game controllers, and then report the results back to me

**Comment by Jjoiner729** [comment]
Number stays 2 but my pc recognizes that something is plugging and unplugging

**Comment by camren-m** [comment]
> Number stays 2 but my pc recognizes that something is plugging and unplugging

Have you uninstalled the Xbox 360 drivers yet?

**Comment by Jjoiner729** [comment]
just did nothing changed

**Comment by camren-m** [comment]
> just did nothing changed

Have you tried plugging your wheel into a different port on your computer?

**Comment by Jjoiner729** [comment]
indeed i have

**Comment by camren-m** [comment]
> indeed i have

What version of Windows are you using currently? (you can find this by typing winver in your search bar and hitting enter)

**Comment by Jjoiner729** [comment]
windows 11 version 21H2

**Comment by camren-m** [comment]
Alright, I'm going to see if I can set up a virtual machine to try and emulate the problem and debug it. Both occurrences of this problem that I've seen have occurred on Windows 11 21H2, so it might be as simple as upgrading your Windows version but I'm not entirely sure yet.

**Comment by Jjoiner729** [comment]
how would I upgrade because I just checked for updates and i am up to date

**Comment by camren-m** [comment]
> how would I upgrade because I just checked for updates and i am up to date

The next version might be an insider version at the moment, so I wouldn't attempt upgrading (because you'd have to enroll in the insider program) until I've confirmed that it is an issue just with 21H2.

**Comment by Jjoiner729** [comment]
im already enrolled in the dev channel and i now see an update

**Comment by camren-m** [comment]
> im already enrolled in the dev channel and i now see an update
> 
> 

Oh, alright. Feel free to try the upgrade and attempt to run the software again.

**Comment by Jjoiner729** [comment]
alrighty will do i reply back with the results

**Comment by cmumme** [comment]
> alrighty will do i reply back with the results

Got it!

**Comment by Jjoiner729** [comment]
im now on 22H2 but it still says 2 raw imput controllers

**Comment by camren-m** [comment]
> im now on 22H2 but it still says 2 raw imput controllers
> 
> 

Hm, is it possible for me to try to remote into your system and debug the problem from there. It's hard telling what the issue is so far.

**Comment by Jjoiner729** [comment]
Never mind I got it who work last night I was just so excited I never put it in here but thanks a lot for your help man!

**Comment by camren-m** [comment]
> Never mind I got it who work last night I was just so excited I never put it in here but thanks a lot for your help man!

No problem! Would you mind telling me how you got it working, just in case somebody else encounters the same problem? Was it just upgrading?

**Comment by RemnantOfFire** [comment]
So I was having the same issue. After updating windows all i had to do was uninstall the device in device manager and plug it back in. Now it works great!
