### ISSUE TITLE
(v1.2.0) Does not work on Revision OS

### ISSUE THREAD

**Issue by FluffyFawn87495** [camren-m/XboxWheelCompatibility#10]
i installed it and i tried to play american truck driving sim but it doesnt recognize it... am i doing something wrong? please help

**Comment by camren-m** [comment]
Can you confirm you installed the latest version? (v1.2.0)

**Comment by FluffyFawn87495** [comment]
yes, its been installed for a couple of hours and i cant figure it out.

**Comment by camren-m** [comment]
When you installed it was there any issues, maybe something similar to #7?

**Comment by FluffyFawn87495** [comment]
Nope i open the software and it says its connected..
![image](https://user-images.githubusercontent.com/65099648/211176892-13aec893-fb19-486e-90a1-871cad7442e3.png)

**Comment by camren-m** [comment]
Hm, have you tried to manually assign controls in american truck driving sim?

**Comment by FluffyFawn87495** [comment]
I tried, it doesn't even think I'm pushing anything..

**Comment by camren-m** [comment]
Odd, do you know if american truck driving sim supports regular xbox one controllers?

**Comment by FluffyFawn87495** [comment]
yes, but is it supposed to see it as an xbox contoller?? I'm not sure if it does.

**Comment by camren-m** [comment]
Yeah, the software basically detects the input from the wheel and turns it into input from a xbox controller. Have you tested it out with other games?

**Comment by FluffyFawn87495** [comment]
ive tried city car driving but it doesnt work on there either..

**Comment by camren-m** [comment]
Alright then, seems like an issue with the input injection phase. I'll see if I can build a debug version once I get home to try and get specifics on the problem.

**Comment by FluffyFawn87495** [comment]
ok, thank you i really apricate it, I have this one and I rly don't want to buy a new one.

**Comment by FluffyFawn87495** [comment]
should i install any other things, like driver?

**Comment by camren-m** [comment]
Nope, you shouldn't need anything else. I'll send you the debug build as soon as I can.

**Comment by FluffyFawn87495** [comment]
what will the debug build do?

**Comment by camren-m** [comment]
It'll just give me some more information on what exactly is going on so I can try to implement a fix,

**Comment by FluffyFawn87495** [comment]
ok! let me know when you're done it :)

**Comment by FluffyFawn87495** [comment]
hey, i dont want to be a bother but have you made it yet?

**Comment by camren-m** [comment]
Yeah you're good. I'm on my way home right now, I'll start when I get home.

**Comment by FluffyFawn87495** [comment]
Ok! take you're time. :)

**Comment by FluffyFawn87495** [comment]
hey, you make any progress yet?

**Comment by Madmatoster** [comment]
I just tried American truck driving demo from Steam and wheel works perfect. FluffyFawn87495, I think you have to install "C++ all in one" and latest .net. I also installed Microsoft Xbox 360 Accessories 1.2.
Look in this thread:
https://linustechtips.com/topic/576104-how-to-use-thrustmaster-ferrari-458-spyder-steering-wheel-on-pc/?do=findComment&comment=15742319
After you install everything, restart your PC and everything should work.

BTW, thank you Cmumme, wheel works great in Assetto Corsa!!!!! Thank you so much!!!

**Comment by FluffyFawn87495** [comment]
Can i have a link for the Xbox 360 thing?

**Comment by Madmatoster** [comment]
Yes, it is in thread. Here it is:
https://www.techspot.com/drivers/driver/file/information/11300/

**Comment by FluffyFawn87495** [comment]
i installed everything and restarted... nothing changed.

**Comment by Madmatoster** [comment]
I can't help you then, sorry. Everything works for me. Windows 11 and Cmumme's app. Try to re-install it.
Only other thing that comes to me is that I have enabled Xbox Configuration Support in "Controler Settings" in Steam.
Maybe that helps

**Comment by FluffyFawn87495** [comment]
I look there but it doesnt detect it as a xbox controller.. do you think you know why?

**Comment by Madmatoster** [comment]
> I look there but it doesnt detect it as a xbox controller.. do you think you know why?

Sorry, I have no idea

**Comment by FluffyFawn87495** [comment]
do you think it’s because my os is a modified version of windows 11?

**Comment by camren-m** [comment]
> do you think it’s because my os is a modified version of windows 11?

That is extremely likely. Can you please elaborate on what you mean by modified?

**Comment by FluffyFawn87495** [comment]
https://www.revi.cc
im using revision os

**Comment by camren-m** [comment]
> https://www.revi.cc
> 
> im using revision os 

Yup, that's most likely your issue. I'm not planning on supporting any other operating systems than Microsoft distributed versions of Windows 10 and above, although you or anyone else interested may open a pull request if they wish to add such a feature. Until somebody does, if you wish to use this software please switch to any Microsoft distributed version of Windows 10 or above.
