### ISSUE TITLE
Failed to start. Verify that you have sufficient privliges to start system services.

### ISSUE THREAD

**Issue by Scionist** [camren-m/XboxWheelCompatibility#12]
How do i fix this issue?

**Comment by camren-m** [comment]
> How do i fix this issue?

When you start the installer, does it prompt you to allow changes to this device or similar?

**Comment by beclugo** [comment]
> > How do i fix this issue?
> 
> When you start the installer, does it prompt you to allow changes to this device or similar?

Pop ups the changes on this device but same error.

**Comment by Azeyyy** [comment]
Anyone find anything I am going to light myself on fire if I don't figure this out.

**Comment by camren-m** [comment]
Duplicate of #7
