### ISSUE TITLE
(v1.2.0) Failure to inject gamepad input

### ISSUE THREAD

**Issue by Truskater1255** [camren-m/XboxWheelCompatibility#13]
So um using the xbox wheel program it says wheel connected and thats it and when i go to city car driving my wheel it wont appear or maybe the settings are wrong ?

**Comment by camren-m** [comment]
> So um using the xbox wheel program it says wheel connected and thats it and when i go to city car driving my wheel it wont appear or maybe the settings are wrong ?

are you the guy using revision os?

**Comment by Truskater1255** [comment]
No

**Comment by camren-m** [comment]
> No

Please try using the solution in #15

**Comment by cmumme** [comment]
> So um using the xbox wheel program it says wheel connected and thats it and when i go to city car driving my wheel it wont appear or maybe the settings are wrong ?

Any users still experiencing this problem, please install the .NET 6.0 runtime [here](https://download.visualstudio.microsoft.com/download/pr/4c5e26cf-2512-4518-9480-aac8679b0d08/523f1967fd98b0cf4f9501855d1aa063/windowsdesktop-runtime-6.0.13-win-x64.exe) and retry the installation.

**Comment by camren-m** [comment]
> No

Have you resolved this issue yet? If so please describe how you did so any other users having this problem know how to fix it.

**Comment by camren-m** [comment]
I'm closing this issue for now but will continue to be subscribed to it. If this issue is still occurring please comment on this issue with any additional information if any, and I will re-open it.
