### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lghttch713** [camren-m/XboxWheelCompatibility#14]
Installed per directions and am getting a "No wheel connected" when I run the Xbox Wheel Compatibility.  I did an  uninstall and reinstalled and got same message.  Have tried multiple USB ports.  Any ideas?

**Comment by beclugo** [comment]
With the Wheel Tester from the Windows Store doesn't detected but once in-game it detects it.

> Installed per directions and am getting a "No wheel connected" when I run the Xbox Wheel Compatibility. I did an uninstall and reinstalled and got same message. Have tried multiple USB ports. Any ideas?

**Comment by lghttch713** [comment]
I fixed my issue...operator error.  I had to update the xbox driver for it and it works perfectly now.  Steering and all buttons.
