### ISSUE TITLE
(v1.2.0) Installed drivers are interfering

### ISSUE THREAD

**Issue by alessiettomatto** [camren-m/XboxWheelCompatibility#15]
I have the Ferrari 458 spider, i went thorugh a lot of sites and i found your tool. Once i installed if i open the program says " No Wheel Connected ", but the steering wheel is connected.

**Comment by camren-m** [comment]
> I have the Ferrari 458 spider, i went thorugh a lot of sites and i found your tool. Once i installed if i open the program says " No Wheel Connected ", but the steering wheel is connected.

What's the exact version of Windows you are using? You can find this by typing winver in your windows program menu and hitting enter.

**Comment by lghttch713** [comment]
Update the Xbox driver for it, I was having the same issue.  I updated the driver for the xbox controller and it all works now as it should.

**Comment by alessiettomatto** [comment]
Thanks for the comment. I am on windows 10.
Yesterday i solved the problem but i didnt have time to answer here on git hub ^^.
Basically the programm of cmumme was the last source i saw on internet, my pc was full of fake drivers or not working. 
I deleted all the drivers and program to do a fresh install, and it worked. So that was the solution for me 😁.
Ps: Your work is amazing guys, keep going!

**Comment by camren-m** [comment]
Thank you! I'll make sure to put a note in the readme to ensure all drivers related to xbox controllers are uninstalled.

**Comment by atennapel** [comment]
Which driver exactly should be used to get this to work? For me it's using:
```
dc1-controller.sys
devauthe.sys
xboxgip.sys
```
But I get "No wheel connected". I tried "Update Driver" but that just says the driver is up-to-date. I'm running Windows version 1809 (OS Build 17763.3887). Can I download the required driver from somewhere?

**Comment by camren-m** [comment]
> Which driver exactly should be used to get this to work? For me it's using:
> 
> ```
> 
> dc1-controller.sys
> 
> devauthe.sys
> 
> xboxgip.sys
> 
> ```
> 
> But I get "No wheel connected". I tried "Update Driver" but that just says the driver is up-to-date. I'm running Windows version 1809 (OS Build 17763.3887). Can I download the required driver from somewhere?

Hey there! Those are the only drivers you should need, but I'd recommend updating your Windows and trying again.

**Comment by atennapel** [comment]
Thanks. I checked it on another PC and it's true, Windows needs to be (I think) 1909+.

**Comment by camren-m** [comment]
> Thanks. I checked it on another PC and it's true, Windows needs to be (I think) 1909+.
> 
> 

Awesome, thanks for the information! I'll be sure to look into it more and see if I can get an exact minimum required version.
