### ISSUE TITLE
Xbox Wheel Compatibility

### ISSUE THREAD

**Issue by Kian100000** [camren-m/XboxWheelCompatibility#17]
Hey there, when I run the MSI, I get an error saying. 
Service "wheel compatibility service'
(WheelCompatibilityService) failed to start, verify that you have sufficient privileges to start system services.

I have run the file multiple times and continuously get this error, I am on Windows 11, Can you please fix this?

**Comment by Kian100000** [comment]
![Screenshot_20230213_052559](https://user-images.githubusercontent.com/125318077/218588681-15c3d433-12c9-4c42-9d64-ef8822d72e4f.png)
There is the screenshot of the error

**Comment by camren-m** [comment]
> ![Screenshot_20230213_052559](https://user-images.githubusercontent.com/125318077/218588681-15c3d433-12c9-4c42-9d64-ef8822d72e4f.png)
> 
> There is the screenshot of the error

What is the specific version of Windows 11 you are running? If you don't know how to find this you can type in winver into your start menu, hit enter, and send me a screenshot of the window that pops up.

**Comment by Kian100000** [comment]
Version 22H2 OS build 22621.1105

**Comment by camren-m** [comment]
> ![Screenshot_20230213_052559](https://user-images.githubusercontent.com/125318077/218588681-15c3d433-12c9-4c42-9d64-ef8822d72e4f.png)
> 
> There is the screenshot of the error

Please try installing the .NET 6.0 runtime [here](https://download.visualstudio.microsoft.com/download/pr/4c5e26cf-2512-4518-9480-aac8679b0d08/523f1967fd98b0cf4f9501855d1aa063/windowsdesktop-runtime-6.0.13-win-x64.exe) and trying the installation again. If this does not work, please see #12.

**Comment by Kian100000** [comment]
Thank You !

**Comment by camren-m** [comment]
> Thank You !

Did this fix your issue?
