### ISSUE TITLE
Verify that you have sufficient privileges to start system services  error ?  

### ISSUE THREAD

**Issue by Dombo690** [camren-m/XboxWheelCompatibility#18]
![Screenshot 2023-02-18 203848](https://user-images.githubusercontent.com/125726311/219848223-23360c0a-9ddd-48e2-9f23-ca9346e67c10.png)

How to fix? Any ideas?
Win 10
Cheers

**Comment by Dombo690** [comment]
nvm just looked at that ltt fix and it worked perfectly.

**Comment by camren-m** [comment]
> nvm just looked at that ltt fix and it worked perfectly.

Awesome!
