### ISSUE TITLE
Unsure how to get this to work.

### ISSUE THREAD

**Issue by whytrabyt** [camren-m/XboxWheelCompatibility#2]
I downloaded the program and installed it then hooked up my 458 spider. But I am getting nothing for inputs. Can you please explain what i need to do to get this up and running? 458 spider on a windows 11 @cmumme

**Comment by whytrabyt** [comment]
think i found my issue 
![image](https://user-images.githubusercontent.com/59097766/208548266-8ec67870-4440-4e57-a113-f9185153faed.png)
not sure if this is meant to happen or no

**Comment by camren-m** [comment]
Thank you for the report! I've actually encountered this issue when helping a friend set this up, and I believe I know a fix. I'll implement it in the next release, which should be within the hour.

**Comment by kinglinklink** [comment]
im also having this issue

**Comment by camren-m** [comment]
Please upgrade to a newer version if you are still having this issue.
