### ISSUE TITLE
"Wheel not detected"

### ISSUE THREAD

**Issue by NOTlazy2k** [camren-m/XboxWheelCompatibility#20]
I have read through all of the previous issues and tried all of the fixes, but one confused me when it says "update xbox drivers". How do you update them.

**Comment by camren-m** [comment]
It's possible your issue is not driver related. Please describe the actual issue you're having.

**Comment by NOTlazy2k** [comment]
I have installed the XboxWheelCompatibility software and it shows "Wheel Connected", but when I go in game it does not show up as a controller. I have tried games like American Truck Simulator, GTA V with Manual Transmission mod. I ran the Wheel Tester application from the Microsoft Store and it works.

When I first plugged in the wheel, I pressed the xbox button and it opened the game bar. Now the xbox button does absolutely nothing, I paired a real controller and xbox button opens game bar. Im not sure if that has anything to do with it.

**Comment by camren-m** [comment]
Do these games support xbox one controllers?

**Comment by NOTlazy2k** [comment]
Yes, I was playing GTA V and ATS with a Xbox controller

**Comment by NOTlazy2k** [comment]
I am on Windows 11, Version 22H2 OS Build 22621.1265

**Comment by camren-m** [comment]
Huh. Do you have any xbox controller related drivers installed?

**Comment by NOTlazy2k** [comment]
I took a break to go eat, came back and it was working. lmfao thanks

**Comment by BROTON21** [comment]
I just tried to have all this work but it says there is " no wheel connected" and I updated all my drivers and am running it with administrator I dont know if im doing something wrong but heres some code 
![image](https://user-images.githubusercontent.com/126312814/221342893-c5a6b6e4-d847-492a-9e84-d0ef0ae97bc7.png)

**Comment by camren-m** [comment]
Please use the 

> I just tried to have all this work but it says there is " no wheel connected" and I updated all my drivers and am running it with administrator I dont know if im doing something wrong but heres some code
> ![image](https://user-images.githubusercontent.com/126312814/221342893-c5a6b6e4-d847-492a-9e84-d0ef0ae97bc7.png)

Please use the latest version [here](https://github.com/cmumme/XboxWheelCompatibility/releases)

**Comment by RedPandaJ** [comment]
How do we actually fix this

**Comment by RedPandaJ** [comment]
I’m on 22h2 windows 10, all drivers updated and the wheel is plugged in

**Comment by camren-m** [comment]
Uninstall any xbox related drivers that aren't included with windows and restart your computer.

**Comment by RedPandaJ** [comment]
K

**Comment by RedPandaJ** [comment]
Will try tommorow as I’m going to bed soon

**Comment by RedPandaJ** [comment]
How do you uninstall drivers?

**Comment by RedPandaJ** [comment]
nvm i deleted them
the wheel is detected, the steering is LT though

**Comment by camren-m** [comment]
are you using version 1.2.0?

**Comment by RedPandaJ** [comment]
yup

**Comment by RedPandaJ** [comment]
im on 22h2 win 10

**Comment by camren-m** [comment]
wdym it's LT?

**Comment by RedPandaJ** [comment]
the steering only registers as the left trigger
left and right steering

**Comment by camren-m** [comment]
Odd, do you have the thrust master ferrari wheel?

**Comment by RedPandaJ** [comment]
yup
458 spider

**Comment by RedPandaJ** [comment]
its on beamng

**Comment by RedPandaJ** [comment]
ive deleted all drivers

**Comment by RedPandaJ** [comment]
Hello?

**Comment by RedPandaJ** [comment]
nvm i fixed it
i had to go into device manager, uninstall windows drivers and unplug the wheel, plug it back in, boot up beam ng and it worked!

**Comment by RedPandaJ** [comment]
thank you so much you saved me an entire wheel!
