### ISSUE TITLE
Wheel not shown in F1-22 and Dirt 2

### ISSUE THREAD

**Issue by realvanion** [camren-m/XboxWheelCompatibility#23]
Hey there,

i installed your tool, but my Spider is will not be shown F1-22 or Dirt 2.

Any Idea?

Best reganrds,
Chris

--
Windows 11 Home 22H2
Installation worked
Wheel Comparibility shows "Wheel connected"
Device Management shows "Xbox Gamingdevice"

**Comment by camren-m** [comment]
Duplicate of #47.
