### ISSUE TITLE
I'm not entirely sure what it means by all xbox drivers not already installed.

### ISSUE THREAD

**Issue by PhyxOG** [camren-m/XboxWheelCompatibility#28]
Could someone please clarify so I don't have to just go around and possibly download the wrong drivers. I'm decent with technology, but I just want to use my wheel.

**Comment by camren-m** [comment]
> Could someone please clarify so I don't have to just go around and possibly download the wrong drivers. I'm decent with technology, but I just want to use my wheel.

If you haven't installed any drivers for the wheel or other xbox accessories you do not have to worry about that notice.

**Comment by PhyxOG** [comment]
thank you, but the app still says wheel not connected. It's the Thrustmaster Ferrari 458 Spider. I have the .NET framework from your link, but something still isn't working right.

**Comment by PhyxOG** [comment]
I have another driver that didn't work properly do I need to get rid of that one for it to read the wheel properly?

**Comment by camren-m** [comment]
> thank you, but the app still says wheel not connected. It's the Thrustmaster Ferrari 458 Spider. I have the .NET framework from your link, but something still isn't working right.

What version of windows are you running? You can find this by typing winver into your start menu.

**Comment by camren-m** [comment]
> I have another driver that didn't work properly do I need to get rid of that one for it to read the wheel properly?

Yes, that should resolve your issue.

**Comment by PhyxOG** [comment]
21H2 is the version

**Comment by PhyxOG** [comment]
How do I get a newer version?

**Comment by camren-m** [comment]
Please try removing the driver before that.

**Comment by PhyxOG** [comment]
ok

**Comment by PhyxOG** [comment]
it works now thank you so much!

**Comment by camren-m** [comment]
> it works now thank you so much!

No problem, enjoy!

**Comment by PhyxOG** [comment]
hate to bother you so much but im trying to use this for CarX Drift, but it still isn't recognizing turning functions or my brake petal. Any suggestions. I tried remapping controls with no success.
