### ISSUE TITLE
Service crash when plugging in wheel

### ISSUE THREAD

**Issue by lingle98** [camren-m/XboxWheelCompatibility#3]
First off, thank you for working on this! I have a Thrustmaster 458 Spider and was disappointed it didn't work out of the box with PC games non-xbox.
I had version 1.1.1. I also noticed in your event logs it reports the version 1.0.0.0(I think that can be set in the AssemblyInfo.cs or maybe the app.manifest? or in the properties of the project before publishing)
I had the service running, was watching it in task manager and services. As soon as I plugged in the wheel, it crashed.
I pulled two events relating to it out of the Application Event Log and have attached them in evtx form.
I was able to start the service again in services after it crashed, but I haven't yet tried it in a game to see if it works.
[WheelCompatibility Crash Logs.zip](https://github.com/cmumme/XboxWheelCompatibility/files/10280583/WheelCompatibility.Crash.Logs.zip)

**Comment by camren-m** [comment]
Hey, thanks for the report! Looks like an issue with gamepad input injection. It's hard isolating what exactly the issue is as Xboxgipsynthetic.dll (the library throwing the error) is not documented at all and has no debugging symbols. Do you happen to have any information on how I might be able to replicate it. System specs and OS version would also be useful.

Also, the version mismatch is just me forgetting to update the version in the installer project (as i've switched from vs installer projects to wix v3 for creating the installer)

**Comment by lingle98** [comment]
Ah, I've never used wix.
[PCSpecs20221221.zip](https://github.com/cmumme/XboxWheelCompatibility/files/10282145/PCSpecs20221221.zip)

I'm attaching another zip with snips of windows info and hardware info.
As far as replicating it, not sure other than I had the service running, then plugged in wheel and saw the service crash.
It's not consistent though. After a restart of the computer I opened services again and saw it start up, and plugged in the wheel again and it didn't crash this time.

**Comment by camren-m** [comment]
> Ah, I've never used wix. [PCSpecs20221221.zip](https://github.com/cmumme/XboxWheelCompatibility/files/10282145/PCSpecs20221221.zip)
> 
> I'm attaching another zip with snips of windows info and hardware info. As far as replicating it, not sure other than I had the service running, then plugged in wheel and saw the service crash. It's not consistent though. After a restart of the computer I opened services again and saw it start up, and plugged in the wheel again and it didn't crash this time.

Weird, has it occurred more than once? Looking at your specs, it's almost identical to mine.

**Comment by lingle98** [comment]
I have not gotten it to happen again. May have just been a glitch in my windows environment that worked itself out with a restart. IT 101 I guess

**Comment by camren-m** [comment]
> I have not gotten it to happen again. May have just been a glitch in my windows environment that worked itself out with a restart. IT 101 I guess

Yup, heisenbugs are real fun stuff. Everything's working fine now though, correct? Your wheel is working properly with everything?

**Comment by lingle98** [comment]
Mostly, though I've noticed one issue with this wheel so far.
![20221221_195746](https://user-images.githubusercontent.com/61987153/209039816-8aba551c-8d65-414e-9f1c-e2c835d24672.jpg)
The button circled on the left and the A button are both showing up as 'Joy A' when mapping in Truck Sim.

**Comment by camren-m** [comment]
> Mostly, though I've noticed one issue with this wheel so far. ![20221221_195746](https://user-images.githubusercontent.com/61987153/209039816-8aba551c-8d65-414e-9f1c-e2c835d24672.jpg) The button circled on the left and the A button are both showing up as 'Joy A' when mapping in Truck Sim.

Yeah, the wheel seems to report those two buttons as the same. (it also does the same for the gear buttons and the buttons on the back of the wheel) There seems to be no way around this at the moment. Thank you very much for reporting these issues, and feel free to let me know if you have any suggestions for features or other bug reports!
