### ISSUE TITLE
Build 1.2.0 Issues

### ISSUE THREAD

**Issue by AmericanBranflakes** [camren-m/XboxWheelCompatibility#32]
When trying to get the wheel (Thrustmaster Spider 458) working in SCS games, Euro and American Truck Sim, they read wheel inputs as z axis inputs identical to the right pedal. Attempted restart and reinstall before contacting.

**Comment by danielpalfrey** [comment]
When mine did this I unplugged the wheel and plugged it back in while the game was running. This did however cause the right click issue I mentioned in my issue request.

**Comment by FutWis** [comment]
> 

Did the 1.1 work

**Comment by FutWis** [comment]
Because I have the same problem

**Comment by camren-m** [comment]
Possible duplicate of #38
