### ISSUE TITLE
this app cant run on your pc

### ISSUE THREAD

**Issue by Pancake1111111** [camren-m/XboxWheelCompatibility#33]
hi, i used to use this application on my old computer which run win 10, since upgrading computer and now having win 11 i now get a message saying "this app cant run on your pc" whenever trying to open the installation, just wondering if you had any fix or anyone else reporting this? thanks alot, pancake.

**Comment by camren-m** [comment]
Please install .NET runtime.

**Comment by camren-m** [comment]
Could also be an issue with your Windows 11 settings. I haven't heard from you, so I'm going to close this. Let me know if you're interested in a potential fix.
