### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by rockbottomies** [camren-m/XboxWheelCompatibility#35]
Hey,
I have downloaded your Xbox Wheel Compatability and it doesn't work for me, I have a wheel, and I have MSI. What do I need to do?
Yours Truly,
Rock.

**Comment by camren-m** [comment]
Have you tried to actually open the MSI?

**Comment by rockbottomies** [comment]
You can open MSI?

**Comment by rockbottomies** [comment]
Wait a minute

**Comment by rockbottomies** [comment]
Yea sorry, for the last few days, I had a massive brain fart. I thought the Runtime thingy was MSI. I will download MSI and if I need more help I'll just write it here.
