### ISSUE TITLE
Doesnt work on assetto corsa

### ISSUE THREAD

**Issue by Smo0o** [camren-m/XboxWheelCompatibility#38]
Tried on a few games and it seems to work just fine as the controller input works, In assetto corsa it shows up when you move the wheel and press the petals in the input menu but in game it just doesnt work

**Comment by theNav3** [comment]
Hey man, I got it working on Assetto Corsa. I was having the same issue at first, but here's what I did to fix it. I downloaded a 3rd party launcher for the game called Content Manager and added it to Steam as a non-Steam game. Then I went into control settings and enabled Steaminput for both Content Manager and the game itself. Then I redefined all controls in Content Manager and the wheel works fine. Note when defining brake and throttle controls you must enable invert on throttle but leave invert turned off on brake. Have fun!

**Comment by BomOnTop** [comment]
> Hey man, I got it working on Assetto Corsa. I was having the same issue at first, but here's what I did to fix it. I downloaded a 3rd party launcher for the game called Content Manager and added it to Steam as a non-Steam game. Then I went into control settings and enabled Steaminput for both Content Manager and the game itself. Then I redefined all controls in Content Manager and the wheel works fine. Note when defining brake and throttle controls you must enable invert on throttle but leave invert turned off on brake. Have fun!

Hey I'm trying to use this myself on Assetto Corsa and I followed all your directions but i seem to be having trouble on it recognizing the wheel buttons on content manager, so it knows what the controller is but the buttons seem to be linking to the same things when it shouldnt, thanks.

**Comment by camren-m** [comment]
This is not an issue with the program, rather with Assetto Corsa. There isn't anything I can do on my side, your best bet is to use the SteamInput/content manager solution.
