### ISSUE TITLE
Issue Report on Ver 1.2.0

### ISSUE THREAD

**Issue by ghost** [camren-m/XboxWheelCompatibility#4]
I am using a Ferrari 458 Spyder racing wheel on windows 10 and the steering wheel registers any movement on the wheel as right-click. The left pedal is also unbound.

**Comment by camren-m** [comment]
Thanks for the report! I'll take a look at this once I'm home again tomorrow.

**Comment by tavion256** [comment]
having same problem

**Comment by camren-m** [comment]
> having same problem
> 
> 

Do any of you know if this problem is also occurring with older versions?

**Comment by tavion256** [comment]
yes

**Comment by camren-m** [comment]
> yes

That's odd, it shouldn't be able to send mouse inputs at all. Is there a possibility that some other software or driver is interfering?

**Comment by tavion256** [comment]
do i need to turn off steam driver

**Comment by camren-m** [comment]
> do i need to turn off steam driver 
> 
> 

I'd recommend it, and then report your results back.

**Comment by tavion256** [comment]
same issues as first person

**Comment by camren-m** [comment]
> same issues as first person

What version of Windows are you running? You can find this by typing winver in your programs menu and hitting enter.

**Comment by tavion256** [comment]
win 10

**Comment by ghost** [comment]
I FIGURED IT OUT. I no longer have the problem, had to fully remove any drivers affecting this and recalibrate the wheel in the windows device manager along with restarting my computer.

**Comment by tavion256** [comment]
HOW

**Comment by tavion256** [comment]
it works thanks bro make a yt video for content
