### ISSUE TITLE
volante funciona como freio nao consigo ajeitar

### ISSUE THREAD

**Issue by gabrielgameer** [camren-m/XboxWheelCompatibility#42]
em todos os jogos que eu avia jogado forza,the crew..etc tinha reconhecido normalmente com o driver mais quando foi no asseto ele reconhece o volante como o gatilho esquerdo assim fica impossivel de jogar ja que toda vez que eu entro o carro fica freiando

**Comment by camren-m** [comment]
Você está usando a versão 1.2.0?

**Comment by camren-m** [comment]
Going to close this as a duplicate.

**Comment by gabrielgameer** [comment]
estou usando a 1.3.0 mais mesmo assim n continua o problema

**Comment by gabrielgameer** [comment]
1.2.0*
