### ISSUE TITLE
volante funciona como freio em jogos steam

### ISSUE THREAD

**Issue by gabrielgameer** [camren-m/XboxWheelCompatibility#44]
estou com a versao 1.2.0 mais mesmo assim o volante continua funcionando comoo freio e nao sei como resolver embora ja saiba que ja reportaram essemesmo erro nao disseram possiveis soluções alem de de utilizar a versao 1.2.0 que e a atual versao instalada no meu pc por favor me deem uma dica de soluçao quero jogar ets2 e asseto

**Comment by camren-m** [comment]
Duplicate.
