### ISSUE TITLE
[11-22H2-I] Installer exits with code 2502. Failure to write files.

### ISSUE THREAD

**Issue by HaldirTv** [camren-m/XboxWheelCompatibility#48]
Hello! I wanted to install the program, but an error pops up.
Windows 11 build 22H2, OS build: 22621.1928. .NET Runtime 6.0 is installed
![image](https://github.com/cmumme/XboxWheelCompatibility/assets/120830944/9c5303e2-25bf-488d-8105-8b4fc2b11d59)

**Comment by camren-m** [comment]
I honestly don't think this is an issue with the program itself. This means there's an issue when writing the program files to the installation directory. Is your program files folder protected in any way?

**Comment by HaldirTv** [comment]
> I honestly don't think this is an issue with the program itself. This means there's an issue when writing the program files to the installation directory. Is your program files folder protected in any way?

Hello! I reinstalled my Windows and everything worked.

**Comment by camren-m** [comment]
Sounds about right! Glad you got your issue fixed.
