### ISSUE TITLE
the wheel is not working

### ISSUE THREAD

**Issue by kinglinklink** [camren-m/XboxWheelCompatibility#5]
i have been trying to use your software for hours to no avail and im wondering if this screenshot is an indicator as to why.
this message comes up everytime i open the compatibility app
![wheel](https://user-images.githubusercontent.com/121367006/209454912-895a7ed2-9b9e-4b19-bec5-efbde34e21f3.PNG)

**Comment by lingle98** [comment]
Looks like it couldn't initialize the Injection Manager. Service needs to run as an administrator?

**Comment by kinglinklink** [comment]
running as admin changes nothing

**Comment by camren-m** [comment]
> i have been trying to use your software for hours to no avail and im wondering if this screenshot is an indicator as to why.
> 
> this message comes up everytime i open the compatibility app
> 
> ![wheel](https://user-images.githubusercontent.com/121367006/209454912-895a7ed2-9b9e-4b19-bec5-efbde34e21f3.PNG)
> 
> 

Please update to a newer version. This issue was fixed in #2.
