### ISSUE TITLE
Not Compatible Windows 11. "failed to start" NEED FIX

### ISSUE THREAD

**Issue by EpicM147** [camren-m/XboxWheelCompatibility#51]
I am admin on my system and I have the wheel plugged in. 
I'm running windows 11 and the wheel doesn't work.

I keep getting the following error.
--------------------------------------------------------------
Service 'Wheel Compatibility Service' 
[WheelCompatibilityService] failed to start. Verify that
you have sufficient privileges to start system service.
--------------------------------------------------------------

**Comment by camren-m** [comment]
Ensure you have .NET 6.0 installed as stated in the readme.

**Comment by camren-m** [comment]
Locking. Let me know if it reoccurs after following my instructions.
