### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 75zzzzz** [camren-m/XboxWheelCompatibility#57]
I am confused as its not working I have installed the driver as said how ever I am unsure if Ive deleted the xbox drivers and if not I dont know how to, after I installed the driver it tells me its connected how ever doesnt work

**Comment by 75zzzzz** [comment]
Its 1.2.1 version

**Comment by camren-m** [comment]
If it says connecting then you're all good on the driver side, but I believe you might be having an issue similar to #39. I'm working on a fix for that now. What games have you tried to play?

**Comment by 75zzzzz** [comment]
Forza 4 on steam

**Comment by camren-m** [comment]
#47 duplicate.
