### ISSUE TITLE
cant make pc see wheel as a wheel again

### ISSUE THREAD

**Issue by wolfinacave** [camren-m/XboxWheelCompatibility#59]
My wheel (Thrustmaster 458 spider) is recognized by my computer as a controller after using Xbox wheel compatibility. The problem is that I can't make the pc not see it as a controller, but as a wheel, even after deleting the app. Now I can't use my wheel the way I used to be able to in Forza Horizon 5. I tried rebooting the system, but that didn't work. Is there something else I need to delete/install?

**Comment by camren-m** [comment]
This is intentional, working on a possible solution in #39/#56.

**Comment by wolfinacave** [comment]
thank you so much its fixed now!
