### ISSUE TITLE
Steering wheel turning like a controller - thrustmaster 458 spider xbox wheel

### ISSUE THREAD

**Issue by saisaisly** [camren-m/XboxWheelCompatibility#62]
Hey,

I just installed the xbox wheel compatibility program, but when I use the wheel in games, it turns like a controller, like using a joystick. I understand that the program is used to emulate a xbox controller but was just wondering if there's a way make the wheel corresponding to the in game wheel, like an actual wheel.
Note that my steering does not have force feedback 

                 Thanks,
                 saisaisly

**Comment by camren-m** [comment]
There is not, but there will be soonish. See #39 and #56.
