### ISSUE TITLE
v1.2.1

### ISSUE THREAD

**Issue by kovalyashka** [camren-m/XboxWheelCompatibility#63]
Hi, I have a problem, error 0x80070666 which says another version of the product is already installed, but I have never installed before
[Xbox_Wheel_Compatibility_20230915180420.log](https://github.com/cmumme/XboxWheelCompatibility/files/12624081/Xbox_Wheel_Compatibility_20230915180420.log)

**Comment by PeanutPal65** [comment]
What did you do to fix this? im having the same issue.
