### ISSUE TITLE
(v1.2.0) Failure to start service when installing

### ISSUE THREAD

**Issue by foxcheezy** [camren-m/XboxWheelCompatibility#7]
Hi so I'm trying to download the program and the older versions work but when I try and install the newer program and it just comes up with this do you know how to fix this if you do could you  pls help
![Screenshot 2022-12-28 184508 - Copy](https://user-images.githubusercontent.com/121540328/209923192-4666a88b-b001-4e5a-b248-c2d61db158e1.png)

**Comment by CJPJD** [comment]
same issue here, previous version worked, I have admin privilege's and windows installer is working correctly.

**Comment by snmoses** [comment]
The same issue, ensured that .NET frameword was installed as well

**Comment by camren-m** [comment]
Thanks for reporting this issue! I think it might have to do with how the installer handles version upgrades. Have you tried uninstalling all previous versions, then running the latest installer?

**Comment by snmoses** [comment]
> Thanks for reporting this issue! I think it might have to do with how the installer handles version upgrades. Have you tried uninstalling all previous versions, then running the latest installer?

This version was the first version of the installer that I downloaded.

**Comment by Truskater1255** [comment]
Please fix this I want to play city car driving for my driving test..

**Comment by Truskater1255** [comment]
Please fix it

**Comment by camren-m** [comment]
I'm working on it.

**Comment by Cwebs123** [comment]
I was just having this same issue, but it started working only after the old version was completely uninstalled, not just deleting the folder.  Once the new V1.2 was installed I just had to go to Services and manually enabled the Wheel Compatibility Service, and it worked.  Btw I really appreciate you making this program because I was struggling for a long time trying to find a solution myself!

**Comment by Truskater1255** [comment]
Please fix this quick as possible I do want to play

**Comment by Truskater1255** [comment]
have you fixed it?

**Comment by snmoses** [comment]
> have you fixed it?

Hello Truskater1255, I am as eager as everyone for this project to be working again, however, as a coding enthusiast myself I would recommend not bothering the developer about fixing this bug in the project. I am very certain as soon as this gets fixed, the developer will let everyone know.

**Comment by camren-m** [comment]
> > have you fixed it?
> 
> 
> 
> Hello Truskater1255, I am as eager as everyone for this project to be working again, however, as a coding enthusiast myself I would recommend not bothering the developer about fixing this bug in the project. I am very certain as soon as this gets fixed, the developer will let everyone know. 

Thank you. I don't get paid for my work on open source projects like this and I'm not obligated to do anything. If you really need something done as soon as possible, you can do it yourself. That's one of the major advantages of open source software, you can do what you wish and add what you need to the software!

**Comment by redfox846** [comment]
Do you know for sure if this is a bug? or could it be something on the users end.

**Comment by Truskater1255** [comment]
Most people are having it

**Comment by snmoses** [comment]
Hello All, 
I've recently found a good fix for this error. Please take a look at this form for instructions on how to fix this error. I've used and tested this method and have found no problems. 
Here's the link: https://linustechtips.com/topic/576104-how-to-use-thrustmaster-ferrari-458-spyder-steering-wheel-on-pc/page/3/#comment-15750074

**Comment by Truskater1255** [comment]
i did whatever that said and now my wheel application will instantly crash and i dont know  how to delete it

**Comment by snmoses** [comment]
> i did whatever that said and now my wheel application will instantly crash and i dont know how to delete it

There’s a few ways remove it. 
1. Go to your task manager and end all instances of XboxWheelCompatibility
2. Go to C:\Program Files(x86) and delete the XboxWheelCompatibility folder
3. Right click on the .msi and click uninstall. 

What do you mean by wheel application? Do you mean the Xbox Wheel Compatibility? Thanks

**Comment by Scionist** [comment]
Having the same issue, someone said to go to services and enable it but it says this:

![image](https://user-images.githubusercontent.com/122709025/212519491-74c610e5-9428-4267-97bb-a471d23c6c91.png)

**Comment by villy173** [comment]
Thank you so much for making this program this really makes my life so much easier!

**Comment by AzwadAbid** [comment]
> Hello All, I've recently found a good fix for this error. Please take a look at this form for instructions on how to fix this error. I've used and tested this method and have found no problems. Here's the link: https://linustechtips.com/topic/576104-how-to-use-thrustmaster-ferrari-458-spyder-steering-wheel-on-pc/page/3/#comment-15750074

This worked. Thank you!

**Comment by camren-m** [comment]
> Hi so I'm trying to download the program and the older versions work but when I try and install the newer program and it just comes up with this do you know how to fix this if you do could you  pls help
> 
> ![Screenshot 2022-12-28 184508 - Copy](https://user-images.githubusercontent.com/121540328/209923192-4666a88b-b001-4e5a-b248-c2d61db158e1.png)
> 
> 

Any users still experiencing this problem, please install the .NET 6.0 runtime [here](https://download.visualstudio.microsoft.com/download/pr/4c5e26cf-2512-4518-9480-aac8679b0d08/523f1967fd98b0cf4f9501855d1aa063/windowsdesktop-runtime-6.0.13-win-x64.exe) and retry the installation.
